version: '3.8'

services:
  web:
    image: python:3.9-bullseye
    container_name: blog_app
    command: >
      sh -c "
      pip install --no-cache-dir django psycopg2-binary djangorestframework-simplejwt django-debug-toolbar dj-database-url openai python-dotenv &&
      python blog/manage.py runserver 0.0.0.0:${PORT}"
    volumes:
      - ../:/app
    working_dir: /app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=blog.settings
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=${PORT}

  db:
    image: postgres:13
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

networks:
  default:
    driver: bridge
